from nlp_engine import get_relevant_articles, analyze_article
from llm_orchestrator import call_llm, generate_prompt


# 🔹 URL COMPARISON (FIXED)
def run_url_comparison(articles):
    valid_articles = []

    for a in articles:
        if a and len(a.get("text", "")) > 100:
            a["features"] = analyze_article(a["text"])
            valid_articles.append(a)

    if len(valid_articles) < 2:
        return {"error": "Not enough valid articles"}

    messages = generate_prompt(
        mode="URL_COMPARISON",
        topic=None,
        articles=valid_articles
    )

    result = call_llm(messages)

    return {
        "articles": valid_articles,
        "comparison": result
    }


# 🔹 TOPIC COMPARISON (FINAL)
def run_topic_comparison(topic: str, articles: list):
    if not articles:
        return {"error": "No articles available"}

    # Step 1: Relevance filtering
    top_articles = get_relevant_articles(topic, articles, top_n=5)

    # Step 2: NLP
    for article in top_articles:
        features = analyze_article(article["text"])
        article["features"] = features

    # Step 3: LLM
    messages = generate_prompt(
        mode="TOPIC_COMPARISON",
        topic=topic,
        articles=top_articles
    )

    comparison = call_llm(messages)

    return {
        "articles": top_articles,
        "comparison": comparison,
        "summary": "Generated by LLM"
    }